global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend monitoring (même s'il n'a pas encore d'endpoint /metrics)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend_a:3000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Frontend monitoring
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend_b:5173']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
